### ISSUE TITLE
Outsource name parsing

### ISSUE THREAD

**Issue by blaiszik** [materials-data-facility/connect_client#11]
Use a library with tests to outsource the name parsing, which can get quite complex
https://github.com/derek73/python-nameparser

**Comment by jgaff** [comment]
Preference is already given to names that the user has separated out into `family` and `given` names with a comma or semicolon. Name parsing is indeed complex, which is why we prefer that the user do it. I don't think another dependency is needed as a fallback; if the current dumb name parsing is insufficient, the user should indicate what the given and family names are using a comma or semicolon.
