### ISSUE TITLE
Set function naming consistency

### ISSUE THREAD

**Issue by blaiszik** [materials-data-facility/connect_client#12]
We currently have some methods of the form set_X and some of the form create_x_block. 

Let's change these for consistency to:
create_mrr_block() --> set_mrr()
create_dc_block() --> set_dc()

**Comment by jgaff** [comment]
This difference is due to differing behavior of the methods:
- `set_X(val)` is a simple `X = val` equivalent (ex. `set_test()`)
- `create_X_block(val1, val2)` takes arguments for an entire block and formats them appropriately, so what a user enters may appear in a slightly altered state (ex. `create_dc_block()`)
- `add_X(val)` implies that `X` holds multiple values and calling the method multiple times does not overwrite (ex. `add_index()`)

The exception to the `create_X` rule is the MRR block, which we do not have a useful helper for. If we're not going to create a useful helper (in the same format as `create_dc_block()`), I'll rename the method.

Does this make sense?

**Comment by jgaff** [comment]
Unless there are issue with this naming scheme, I'm closing this issue.
