### ISSUE TITLE
Allow list of services to be passed to add_service()

### ISSUE THREAD

**Issue by blaiszik** [materials-data-facility/connect_client#14]
add_data_source() already accepts a list, so add_service() only accepting strings seems a bit surprising. Certainly saves a bit of effort if you can pass a list.

**Comment by jgaff** [comment]
`add_service()` only accepts one service at a time because services may accept additional configuration parameters. For example, the service `citrine` accepts the field `public` to control data access. It would be more confusing to have multiple configuration dictionaries, or have `add_service()` sometimes accept a list (if there is no additional configuration) and sometimes not.
`add_data_source()` and similar methods accept lists for convenience because there are no other parameters.
